package com.drumond.rentalcar.utilities;

/**
 * Constants used around the whole project.
 */
public class Constants {
    /**
     * The identification number generated by database.
     */
    public static final String ID = "id";
    /**
     * The signed user identifier key
     */
    public static final String TOKEN = "token";
    /**
     * The name of the user.
     */
    public static final String NAME = "name";
    /**
     * The username.
     */
    public static final String CODE = "code";
    /**
     * The car brand.
     */
    public static final String BRAND = "brand";
    public static final String SEGMENT = "segment";
    public static final String HEADER_FORBIDDEN = "Action not allowed";
    public static final String HEADER_USER_NOT_FOUND = "User not found";
    public static final String BODY_LACK_PERMITIONS = "You do not have enough permitioms to perform this operation.";
}
