package com.drumond.rentalcar.utilities;

/**
 * Constants used around the whole project.
 */
public class Constants {
    /**
     * The identification number generated by database.
     */
    public static final String ID = "id";
    /**
     * The signed user identifier key
     */
    public static final String TOKEN = "token";
}
